"use strict";
//Rule: Database element name=object property name(should be in caps)
Object.defineProperty(exports, "__esModule", { value: true });
exports.auroraContractDetailsElements = void 0;
/**
 * Used to create an element object of aurora contract details page
 *
 * @author somnath.k
 *
 *
 */
exports.auroraContractDetailsElements = {
    SAVE_AS_DRAFT_BTTN: "Auro_Repository_Contract_Details/SAVE_AS_DRAFT_BTTN",
    DNY_REPOSITORY_DRAFT_STATUS_HEADER: "Auro_Repository_Contract_Details/DNY_REPOSITORY_DRAFT_STATUS_HEADER",
    DNY_AURORA_CONTRACT_NUMBER: "Auro_Repository_Contract_Details/DNY_AURORA_CONTRACT_NUMBER",
    BOOKMARK_ICON: "Auro_Repository_Contract_Details/BOOKMARK_ICON",
    CONTRACT_DISABLED_MENU_LIST: "Auro_Repository_Contract_Details/CONTRACT_DISABLED_MENU_LIST",
    DNY_SAVE_AS_DRAFT_ERROR_MSG: "Auro_Repository_Contract_Details/DNY_SAVE_AS_DRAFT_ERROR_MSG",
    CONTRACT_CATEGORY_DROPDOWN: "Auro_Repository_Contract_Details/CONTRACT_CATEGORY_DROPDOWN",
    COMMON_DROPDOWN_LIST: "Auro_Repository_Contract_Details/COMMON_DROPDOWN_LIST",
    CLEAR_CONTRACT_CATEGORY_VALUE: "Auro_Repository_Contract_Details/CLEAR_CONTRACT_CATEGORY_VALUE",
    FOLDER_DROPDOWN: "Auro_Repository_Contract_Details/FOLDER_DROPDOWN",
    MINIMUM_MANDATORY_DROPDOWN_FIELDS: "Auro_Repository_Contract_Details/MINIMUM_MANDATORY_DROPDOWN_FIELDS",
    GRID_CONTRACT_NUMBER_FILTER_SEARCH_BOX: "Repository/GRID_CONTRACT_NUMBER_FILTER_SEARCH_BOX",
    GRID_CONTRACT_CATEGORY_DROPDOWN: "Repository/GRID_CONTRACT_CATEGORY_DROPDOWN",
    GRID_CONTRACT_CATEGORY_DROPDOWN_OPTION_LIST: "Repository/GRID_CONTRACT_CATEGORY_DROPDOWN_OPTION_LIST",
    MINIMUM_MANDATORY_DROPDOWN_FIELD_METADATA: "Auro_Repository_Contract_Details/MINIMUM_MANDATORY_DROPDOWN_FIELD_METADATA",
    CONTRACT_DETAILS_HEADER_LIST: "Auro_Repository_Contract_Details/CONTRACT_DETAILS_HEADER_LIST",
    DNY_AURORA_PARTICULAR_HEADER: "Auro_Repository_Contract_Details/DNY_AURORA_PARTICULAR_HEADER",
    DNY_AURORA_SUBHEADER_LIST: "Auro_Repository_Contract_Details/DNY_AURORA_SUBHEADER_LIST",
    DNY_AURORA_METADATA_INPUT: "Auro_Repository_Contract_Details/DNY_AURORA_METADATA_INPUT",
    COMMON_DROPDOWN_SEARCH_BOX: "Auro_Repository_Contract_Details/COMMON_DROPDOWN_SEARCH_BOX",
    CALENDAR_CURRENT_DAY: "Auro_Repository_Contract_Details/CALENDAR_CURRENT_DAY",
    COMBINED_DAY_MONTH_YEAR: "Auro_Repository_Contract_Details/COMBINED_DAY_MONTH_YEAR",
    CURRENT_RANGE_YEAR_MONTH_DAY_OPTION_LIST: "Auro_Repository_Contract_Details/CURRENT_RANGE_YEAR_MONTH_DAY_OPTION_LIST",
    CONTRACT_EXPIRATION_DATE_FIELD: "Auro_Repository_Contract_Details/CONTRACT_EXPIRATION_DATE_FIELD",
    DNY_NEW_CONTRACT_NUMBER_AURORA: "Auro_Repository_Contract_Details/DNY_NEW_CONTRACT_NUMBER_AURORA",
    CONTRACTING_PARTY_HEADER: "Auro_Repository_Contract_Details/CONTRACTING_PARTY_HEADER",
    SAVE_BUTTON: "Auro_Repository_Contract_Details/SAVE_BUTTON",
    MENU_SWITCH_POPUP: "Auro_Repository_Contract_Details/MENU_SWITCH_POPUP",
    FIRST_CONTRACT_SAVE_TOASTER: "Auro_Repository_Contract_Details/FIRST_CONTRACT_SAVE_TOASTER",
    FILL_ALL_MANDATORY_POPUP: "Auro_Repository_Contract_Details/FILL_ALL_MANDATORY_POPUP",
    FILL_ALL_MANDATORY_POPUP_OK_BTTN: "Auro_Repository_Contract_Details/FILL_ALL_MANDATORY_POPUP_OK_BTTN",
    ALL_FIELDS_MANDATORY_SYMBOL_BASEDON_ERROR_MSG: "Auro_Repository_Contract_Details/ALL_FIELDS_MANDATORY_SYMBOL_BASEDON_ERROR_MSG",
    ALL_FIELDS_MANDATORY_ERROR_MSG: "Auro_Repository_Contract_Details/ALL_FIELDS_MANDATORY_ERROR_MSG",
    AURORA_LOADER: "Auro_Repository_Contract_Details/AURORA_LOADER",
    //****************************** AURORA-49 related webelements ***********************************/
    OCR_LOADER: "Auro_Repository_Contract_Details/OCR_LOADER",
    OCR_SUCCESSFUL_ICON: "Auro_Repository_Contract_Details/OCR_SUCCESSFUL_ICON",
    OCR_SUCCESS_TOAST_MSG: "Auro_Repository_Contract_Details/OCR_SUCCESS_TOAST_MSG",
    BROWSER_FILE: "Basic_Information/BROWSER_FILE",
    UPLOAD_FAILED_ALERT: "Repository/UPLOAD_FAILED_ALERT",
    UPLOAD_FILE_ERRMSG_OK_BUTTON: "Repository/UPLOAD_FILE_ERRMSG_OK_BUTTON",
    DIGITAL_CONTRACT_DOCUMENT: "Repository_Contract_Details/DIGITAL_CONTRACT_DOCUMENT",
    CONTRACT_LINK: "Repository/CONTRACT_LINK",
    CONTRACT_SOURCE: "Repository_grid/CONTRACT_SOURCE",
    CONTRACT_TITLE_NEW: "Auro_Repository_Contract_Details/CONTRACT_TITLE_NEW",
    SAVE_AS_DRAFT_BUTTON: "Repository_Contract_Details/SAVE_AS_DRAFT_BUTTON",
    SELECTED_DAY: "Auro_Repository_Contract_Details/SELECTED_DAY",
    //****************************** End of AURORA-49 related webelements ***********************************/
    /*********************************AURORA-54 starts*********************************************************/
    ALL_CONTRACT_NUMBER_LINK: "Auro_Repository_Contract_Details/ALL_CONTRACT_NUMBER_LINK",
    CHANGES_POPUP_SWITCH_MENU: "Auro_Repository_Contract_Details/CHANGES_POPUP_SWITCH_MENU",
    CLOSE_CHANGES_POPUP_SWITCH_MENU: "Auro_Repository_Contract_Details/CLOSE_CHANGES_POPUP_SWITCH_MENU",
    OK_BTTN_CHANGES_POPUP_SWITCH_MENU: "Auro_Repository_Contract_Details/OK_BTTN_CHANGES_POPUP_SWITCH_MENU",
    CONTRACT_TOTAL_VALUE_FIELD: "Auro_Repository_Contract_Details/CONTRACT_TOTAL_VALUE_FIELD",
    CONTRACT_TOTAL_VALUE_MAX_ERR_MSG: "Auro_Repository_Contract_Details/CONTRACT_TOTAL_VALUE_MAX_ERR_MSG",
    REVISION_COMMENT_BOX: "Auro_Repository_Contract_Details/REVISION_COMMENT_BOX",
    REVISION_COMMENT_SUBMIT: "Auro_Repository_Contract_Details/REVISION_COMMENT_SUBMIT",
    CONTRACT_DETAILS_MENU: "Auro_Repository_Contract_Details/CONTRACT_DETAILS_MENU",
    /*********************************AURORA-54 Ends*********************************************************/
    //****************************** AURORA-554 *******************************************************/
    CP_MANDATORY_MSG: "Auro_Repository_Contract_Details/CP_MANDATORY_MSG",
    CP_MANDATORY_SYMBOL: "Auro_Repository_Contract_Details/CP_MANDATORY_SYMBOL",
    CP_SEARCH_FIELD: "Auro_Repository_Contract_Details/CP_SEARCH_FIELD",
    CP_SEARCH_LIST: "Auro_Repository_Contract_Details/CP_SEARCH_LIST",
    CP_FIRST_OPTIN_AUTOSUGSTN: "Auro_Repository_Contract_Details/CP_FIRST_OPTIN_AUTOSUGSTN",
    CP_CARD: "Auro_Repository_Contract_Details/CP_CARD",
    CP_TYPE_DROPDOWN: "Auro_Repository_Contract_Details/CP_TYPE_DROPDOWN",
    CP_TYPE_LIST: "Auro_Repository_Contract_Details/CP_SEARCH_LIST",
    CP_SELECT_ADDRESS_DROPDOWN: "Auro_Repository_Contract_Details/CP_SELECT_ADDRESS_DROPDOWN",
    CP_SELECT_CONTACT_DROPDOWN: "Auro_Repository_Contract_Details/CP_SELECT_CONTACT_DROPDOWN",
    CP_SELECT_ADDRESS: "Auro_Repository_Contract_Details/CP_SELECT_ADDRESS",
    CP_SELECT_CONTACT: "Auro_Repository_Contract_Details/CP_SELECT_CONTACT",
    CP_NAME_IN_CP_CARD: "Auro_Repository_Contract_Details/CP_NAME_IN_CP_CARD",
    CP_RESTRICTED_PARTY_SCREEN: "Auro_Repository_Contract_Details/CP_RESTRICTED_PARTY_SCREEN",
    CP_PRIMARY_TAG: "Auro_Repository_Contract_Details/CP_PRIMARY_TAG",
    CP_CARD_OPTIONS: "Auro_Repository_Contract_Details/CP_CARD_OPTIONS",
    CP_ADDRESS_ICON: "Auro_Repository_Contract_Details/CP_ADDRESS_ICON",
    CP_CONTACT_ICON: "Auro_Repository_Contract_Details/CP_CONTACT_ICON",
    CP_REMOVE_OPTION: "Auro_Repository_Contract_Details/CP_REMOVE_OPTION",
    CP_MARK_AS_PRIMARY: "Auro_Repository_Contract_Details/CP_MARK_AS_PRIMARY",
    CP_ONE_CP_MANDTRY_TOAST_MSG: "Auro_Repository_Contract_Details/CP_ONE_CP_MANDTRY_TOAST_MSG",
    CP_TEN_CPCARDS: "Auro_Repository_Contract_Details/CP_TEN_CPCARDS",
    CP_CANNOT_ADD_TOAST_MSG: "Auro_Repository_Contract_Details/CP_CANNOT_ADD_TOAST_MSG",
    CP_TO_SELECT_AFTR_TEN_CPS: "Auro_Repository_Contract_Details/CP_TO_SELECT_AFTR_TEN_CPS",
    CP_MAX_TEN_CPS_ARE_ALLOWED_MSG: "Auro_Repository_Contract_Details/CP_MAX_TEN_CPS_ARE_ALLOWED_MSG",
    CP_COUNT: "Auro_Repository_Contract_Details/CP_COUNT",
    EXPAND_OR_COLLAPSE_DOCUMENT_PANEL: "Auro_Repository_Contract_Details/EXPAND_OR_COLLAPSE_DOCUMENT_PANEL",
    PREVIEW_DROPDOWN: "Auro_Repository_Document/PREVIEW_DROPDOWN",
    CP_REMOVE_POPUP: "Auro_Repository_Contract_Details/CP_REMOVE_POPUP",
    CP_REMOVE_CANCEL_BUTTON: "Auro_Repository_Contract_Details/CP_REMOVE_CANCEL_BUTTON",
    CP_REMOVE_BUTTON: "Auro_Repository_Contract_Details/CP_REMOVE_BUTTON",
    CP_NO_MATCHING_MSG: "Auro_Repository_Contract_Details/CP_NO_MATCHING_MSG",
    CP_NAME_ON_CPCARD: "Auro_Repository_Contract_Details/CP_NAME_ON_CPCARD",
    DNY_CP_NAME_IN_SEARCH_LIST: "Auro_Repository_Contract_Details/DNY_CP_NAME_IN_SEARCH_LIST",
    CP_SINGLE_COUNT_AFTER_SAVE: "Auro_Repository_Contract_Details/CP_SINGLE_COUNT_AFTER_SAVE",
    CP_NO_MANDTRY_IN_CPCARD: "Auro_Repository_Contract_Details/CP_NO_MANDTRY_IN_CPCARD",
    CP_TYPE_SUBTYPE_DISPLAY: "Auro_Repository_Contract_Details/CP_TYPE_SUBTYPE_DISPLAY",
    APP_SETTINGS_SAVE_BUTTON: "Product_configuration/APP_SETTINGS_SAVE_BUTTON",
    APP_SETTINGS_CONFIRM_POPUP: "Product_configuration/APP_SETTINGS_CONFIRM_POPUP",
    APP_SETTINGS_CONFRM_POPUP_PROCEED_BTN: "Product_configuration/APP_SETTINGS_CONFRM_POPUP_PROCEED_BTN",
    APP_SETTINGS_SUCCESS_OK_BUTTON: "Product_configuration/APP_SETTINGS_SUCCESS_OK_BUTTON",
    CP_SEARCH_LOADING: "Auro_Repository_Contract_Details/CP_SEARCH_LOADING",
    CP_COUNT_ZERO: "Auro_Repository_Contract_Details/CP_COUNT_ZERO",
    CP_CARD_LIST: "Auro_Repository_Contract_Details/CP_CARD_LIST",
    CP_ADDED_TICK: "Auro_Repository_Contract_Details/CP_ADDED_TICK",
    //****************************** AURORA-554 *******************************************************/
    //****************************** AURORA-603 Starts *******************************************************/
    MSR_LINK: "Auro_Repository_Contract_Details/MSR_LINK",
    MSR_COMMON_LINKS_XPATH: "Auro_Repository_Contract_Details/MSR_COMMON_LINKS_XPATH",
    CP_TOP_CARD: "Auro_Repository_Contract_Details/CP_TOP_CARD",
    NO_MSR_LABEL_ON_TOP_CP_CARD: "Auro_Repository_Contract_Details/NO_MSR_LABEL_ON_TOP_CP_CARD",
    MSR_ALERT_POPUP: "Auro_Repository_Contract_Details/MSR_ALERT_POPUP",
    MSR_FORM: "Auro_Repository_Contract_Details/MSR_FORM",
    MSR_FORM_CLOSE: "Auro_Repository_Contract_Details/MSR_FORM_CLOSE",
    CP_CARDS: "Auro_Repository_Contract_Details/CP_CARDS",
    //****************************** AURORA-603 Ends *******************************************************/
    //****************************** AURORA-97 starts *******************************************************/
    DISABLED_PUBLISH: "Auro_Repository_Contract_Details/DISABLED_PUBLISH",
    UNSAVED_POPUP: "Auro_Repository_Contract_Details/UNSAVED_POPUP",
    PUBLISH_BTTN: "Aurora_Repository/PUBLISH_BTTN",
    PUBLISH_POPUP: "Auro_Repository_Contract_Details/PUBLISH_POPUP",
    EMAIL_POPUP: "Aurora_Repository/EMAIL_POPUP",
    EMAIL_SEND_BTTN: "Aurora_Repository/EMAIL_SEND_BTTN",
    EMAIL_TO_FIELD: "Aurora_Repository/EMAIL_TO_FIELD",
    EMAIL_SUBJECT_FIELD: "Aurora_Repository/EMAIL_SUBJECT_FIELD",
    EMAIL_BCC_FIELD: "Aurora_Repository/EMAIL_BCC_FIELD",
    EMAIL_CC_FIELD: "Aurora_Repository/EMAIL_CC_FIELD",
    PUBLISH_POPUP_CANCEL_BTTN: "Auro_Repository_Contract_Details/PUBLISH_POPUP_CANCEL_BTTN",
    CONTRACT_PUBLISHED_TOASTER_MSG: "Auro_Repository_Contract_Details/CONTRACT_PUBLISHED_TOASTER_MSG",
    PUBLISH_POPUP_ALTER_MSG: "Auro_Repository_Contract_Details/PUBLISH_POPUP_ALTER_MSG",
    AUTO_RENEWAL_DROPDOWN: "Auro_Repository_Contract_Details/AUTO_RENEWAL_DROPDOWN",
    PUBLISH_BTTN_IN_POPUP: "Auro_Repository_Contract_Details/PUBLISH_BTTN_IN_POPUP",
    COMMENT_MANDATORY_ERROR_MSG: "Auro_Repository_Contract_Details/COMMENT_MANDATORY_ERROR_MSG",
    COMMENT_MANDATORY_SYMBOL: "Auro_Repository_Contract_Details/COMMENT_MANDATORY_SYMBOL",
    COMMENT_BOX_PUBLISH_POPUP: "Auro_Repository_Contract_Details/COMMENT_BOX_PUBLISH_POPUP",
    PUBLISH_POPUP_ALTER_NO_OPTION: "Auro_Repository_Contract_Details/PUBLISH_POPUP_ALTER_NO_OPTION",
    PUBLISH_POPUP_INFORM_NO_OPTION: "Auro_Repository_Contract_Details/PUBLISH_POPUP_INFORM_NO_OPTION",
    ALERT_ADDED_TOASTER_MSG: "Auro_Repository_Contract_Details/ALERT_ADDED_TOASTER_MSG",
    PUBLISH_POPUP_ALTER_YES_OPTION: "Auro_Repository_Contract_Details/PUBLISH_POPUP_ALTER_YES_OPTION",
    PUBLISH_POPUP_INFORM_YES_OPTION: "Auro_Repository_Contract_Details/PUBLISH_POPUP_INFORM_YES_OPTION",
    ALL_FIELDS_IN_EMAIL_POPUP: "Auro_Repository_Contract_Details/ALL_FIELDS_IN_EMAIL_POPUP",
    DNY_MANDATORY_FIELD_ERROR_MSG: "Auro_Repository_Contract_Details/DNY_MANDATORY_FIELD_ERROR_MSG",
    REMOVE_EMAILID: "Auro_Repository_Contract_Details/REMOVE_EMAILID",
    EMAIL_ID_CHIPS: "Auro_Repository_Contract_Details/EMAIL_ID_CHIPS",
    EMAIL_MORE_THAN_255_CHAR_ERR_MSG: "Auro_Repository_Contract_Details/EMAIL_MORE_THAN_255_CHAR_ERR_MSG",
    EMAIL_ID_MORE_THAN_500_ERR_MSG: "Auro_Repository_Contract_Details/EMAIL_ID_MORE_THAN_500_ERR_MSG",
    SUBJECT_VAL_MORE_THAN_255_CHAR_ERR_MSG: "Auro_Repository_Contract_Details/SUBJECT_VAL_MORE_THAN_255_CHAR_ERR_MSG",
    EMAIL_BODY_FIELD: "Auro_Repository_Contract_Details/EMAIL_BODY_FIELD",
    CHAR_5000_OF_5000_MSG: "Auro_Repository_Contract_Details/CHAR_5000_OF_5000_MSG",
    FILE_5MB_SIZE_EXCEED_LIMIT_POPUP: "Auro_Repository_Contract_Details/FILE_5MB_SIZE_EXCEED_LIMIT_POPUP",
    REMOVE_ATTACHEMENT_ICON: "Auro_Repository_Contract_Details/REMOVE_ATTACHEMENT_ICON",
    DNY_UPLOADED_ATTACHMENT_MAIL: "Auro_Repository_Contract_Details/DNY_UPLOADED_ATTACHMENT_MAIL",
    CANCEL_EMAIL_POPUP: "Auro_Repository_Contract_Details/CANCEL_EMAIL_POPUP",
    SKIP_EMAIL_BTTON_POPUP: "Auro_Repository_Contract_Details/SKIP_EMAIL_BTTON_POPUP",
    CANCEL_BTTN_SKIP_MAIL_POPUP: "Auro_Repository_Contract_Details/CANCEL_BTTN_SKIP_MAIL_POPUP",
    PUBLISH_MAIL_SENT_TOASTER_MSG: "Auro_Repository_Contract_Details/PUBLISH_MAIL_SENT_TOASTER_MSG",
    //****************************** AURORA-97 Ends *******************************************************/
    /********************************AURORA-2975 :- Starts *************************************************/
    CREATE_CP_BTTN: "Aurora_Contract_Details/CREATE_CP_BTTN",
    FIRST_CP_TYPE_LIST: "Aurora_Contract_Details/FIRST_CP_TYPE_LIST",
    ADD_CP_OVERLAY: "Aurora_Contract_Details/ADD_CP_OVERLAY",
    OVERLAY_CANCEL_BTTN: "Aurora_Contract_Details/OVERLAY_CANCEL_BTTN",
    MAIN_FORM_FIRST_FIELD: "Aurora_Contract_Details/MAIN_FORM_FIRST_FIELD",
    OVERLAY_SUBMIT_BTTN: "Aurora_Contract_Details/OVERLAY_SUBMIT_BTTN",
    CP_ADDED_TOASTER_MSG: "Aurora_Contract_Details/CP_ADDED_TOASTER_MSG",
    DISABLED_SUBMIT_BTTN: "Aurora_Contract_Details/DISABLED_SUBMIT_BTTN",
    OVERLAY_FIRST_HEADER: "Aurora_Contract_Details/OVERLAY_FIRST_HEADER",
    FIRST_FIELD_IN_ATL: "Aurora_Contract_Details/FIRST_FIELD_IN_ATL",
    ATL_FORM_UNFILLED_MSG: "Aurora_Contract_Details/ATL_FORM_UNFILLED_MSG",
    ATLEAST_ONE_ATL_MSG: "Aurora_Contract_Details/ATLEAST_ONE_ATL_MSG",
    OVERLAY_HEADER_LIST: "Aurora_Contract_Details/OVERLAY_HEADER_LIST",
    DNY_OVERLAY_PARTICULAR_HEADER: "Aurora_Contract_Details/DNY_OVERLAY_PARTICULAR_HEADER",
    DNY_METADATA_LIST: "Aurora_Contract_Details/DNY_METADATA_LIST",
    CP_AUTO_SUGG_LIST: "Aurora_Contract_Details/CP_AUTO_SUGG_LIST",
    DNY_PARTICULAR_CP_NAME_IN_CP_CARD: "Aurora_Contract_Details/DNY_PARTICULAR_CP_NAME_IN_CP_CARD",
    UPLOAD_DOC_INLINE_ERROR_MSG: "Aurora_Contract_Details/UPLOAD_DOC_INLINE_ERROR_MSG",
    UPLOAD_CROSS_ICON: "Aurora_Contract_Details/UPLOAD_CROSS_ICON",
    UPLOAD_REPLACE_BTTN: "Aurora_Contract_Details/UPLOAD_REPLACE_BTTN",
    UPLOAD_PROGRESS_BAR: "Aurora_Contract_Details/UPLOAD_PROGRESS_BAR",
    OVERLAY_MANDATORY_SYMBOL: "Aurora_Contract_Details/OVERLAY_MANDATORY_SYMBOL",
    OVERLAY_MANDATORY_MESSAGE: "Aurora_Contract_Details/OVERLAY_MANDATORY_MESSAGE",
    DISCARD_CHANGES_POPUP: "Aurora_Contract_Details/DISCARD_CHANGES_POPUP"
    /********************************AURORA-2975 :- Ends *************************************************/
};
