/**
 * Used to create an element object of add milestone page
 * 
 * @author somnath.k
 * 
 * 
 */
 export let addMilestoneElements = {
   MILESTONE_MENU:"Milestone/MILESTONE_MENU",
   MILESTONE_ADD_ICON:"Milestone/MILESTONE_ADD_ICON",
   MILESTONE_ADD_NEW_BTTN:"Milestone/MILESTONE_ADD_NEW_BTTN",
   MILESTONE_CROSS_ICON:"Milestone/MILESTONE_CROSS_ICON",
   DISCARD_NO_OPTION:"Milestone/DISCARD_NO_OPTION",
   DISCARD_YES_OPTION:"Milestone/DISCARD_YES_OPTION",
   MILESTONE_OVERLAY_CANCEL_BTTN:"Milestone/MILESTONE_OVERLAY_CANCEL_BTTN",
   MILESTONE_OVERLAY_SAVE_BTTN:"Milestone/MILESTONE_OVERLAY_SAVE_BTTN",
   MILESTONE_OVERLAY_CLEAR_ALL_ICON:"Milestone/MILESTONE_OVERLAY_CLEAR_ALL_ICON",
   MILESTONE_OVERLAY_PLANNED_STATUS_VAL:"Milestone/MILESTONE_OVERLAY_PLANNED_STATUS_VAL",
   MILESTONE_OVERLAY_PAYABLE_MTYPE_VAL:"Milestone/MILESTONE_OVERLAY_PAYABLE_MTYPE_VAL",
   MILESTONE_OVERLAY_PRODUCT_DTYPE_VAL:"Milestone/MILESTONE_OVERLAY_PRODUCT_DTYPE_VAL",
   MILESTONE_OVERLAY_BEFORE_RADIO_CHKD:"Milestone/MILESTONE_OVERLAY_BEFORE_RADIO_CHKD",
   MILESTONE_OVERLAY_5DAYS_SDAY_VAL:"Milestone/MILESTONE_OVERLAY_5DAYS_SDAY_VAL",
   MILESTONE_OVERLAY_ON_RADIO_BTTN:"Milestone/MILESTONE_OVERLAY_ON_RADIO_BTTN",
   OVERLAY_HEADER_LIST:"Milestone/OVERLAY_HEADER_LIST",
   DNY_OVERLAY_PARTICULAR_HEADER:"Milestone/DNY_OVERLAY_PARTICULAR_HEADER",
   DNY_METADATA_LIST:"Milestone/DNY_METADATA_LIST"


 }