"use strict";
//Rule: Database element name=object property name(should be in caps)
Object.defineProperty(exports, "__esModule", { value: true });
exports.contractDetailsElements = void 0;
/**
 * Used to create an element object of contract details page
 *
 * @author somnath.k
 *
 *
 */
exports.contractDetailsElements = {
    EMAIL_ADDRESS_TEXTBOX: "Login/EMAIL_ADDRESS_TEXTBOX",
    PASSWORD_TEXTBOX: "Login/PASSWORD_TEXTBOX",
    LOGIN_BUTTON: "Login/LOGIN_BUTTON",
    REPOSITORY_GRID_PAGE: "Repository/REPOSITORY_GRID_PAGE",
    SELECT_CLM_PRODUCT: "Product_Section/SELECT_CLM_PRODUCT",
    SELECT_REPOSITORY_TAB: "CLM_Home/SELECT_REPOSITORY_TAB",
    REPO_STATUS_DROPDOWN: "Repository/REPO_STATUS_DROPDOWN",
    DYN_REPO_STATUS_VALUE: "Repository/DYN_REPO_STATUS_VALUE",
    FIRST_CONTRACT_LINK: "Repository/FIRST_CONTRACT_LINK",
    FIRST_CONTRACT_LINK_HAVING_AMENDMENT: "Repository/FIRST_CONTRACT_LINK_HAVING_AMENDMENT",
    REDIRECT_TO_AURORA_LINK: "Repository/REDIRECT_TO_AURORA_LINK",
    CONTRACT_LEFT_MENU_LIST: "Repository/CONTRACT_LEFT_MENU_LIST",
    DYN_PARTICULAR_LEFT_MENU: "Repository/DYN_PARTICULAR_LEFT_MENU",
    METADATA_VIEW_HEADER: "Aurora_Contract_Details/METADATA_VIEW_HEADER",
    AURORA_CONTRACT_DETAILS_TAB: "Aurora_Contract_Details/AURORA_CONTRACT_DETAILS_TAB",
    CONTRACT_DETAILS_ERROR_TOASTER: "Aurora_Contract_Details/CONTRACT_DETAILS_ERROR_TOASTER",
    CLOSE_REPO_CONTRACT: "Repository/CLOSE_REPO_CONTRACT",
    ADD_TO_WATCHLIST: "Repository/ADD_TO_WATCHLIST",
    DNY_OLD_CONTRACT_NUMBER: "Repository/DNY_OLD_CONTRACT_NUMBER",
    HOME_TAB: "CLM_Home/HOME_TAB",
    COMMON_DASHBOARD: "CLM_Home/COMMON_DASHBOARD",
    MYWATCHLIST_WIDGET: "Dashboard/MYWATCHLIST_WIDGET",
    MYWATCHLIST_SEARCHBOX: "Dashboard/MYWATCHLIST_SEARCHBOX",
    MYWATCHLIST_SEARCH_ICON: "Dashboard/MYWATCHLIST_SEARCH_ICON",
    DNY_MYWATCHLIST_FIRST_CONTRACT_NUMBER: "Dashboard/DNY_MYWATCHLIST_FIRST_CONTRACT_NUMBER",
    SUMMARY_FIRST_MENU: "Repository_Contract_Details/SUMMARY_FIRST_MENU",
    ALERTS_AND_REMINDER_TAB: "CLM_Home/ALERTS_AND_REMINDER_TAB",
    ALERTS_EXPAND_ICON: "AlertsandReminder/ALERTS_EXPAND_ICON",
    ALERT_CONTRACT_NUMBER_LINK: "AlertsandReminder/ALERT_CONTRACT_NUMBER_LINK",
    UPLOAD_CONTRACT_BTTN: "Repository/UPLOAD_CONTRACT_BTTN",
    TYPE_DROPDOWN: "Repository_Create_Contract/TYPE_DROPDOWN",
    TYPE_DROPDOWN_LIST: "Repository_Create_Contract/TYPE_DROPDOWN_LIST",
    DYN_PARTICULAR_TYPE: "Repository_Create_Contract/DYN_PARTICULAR_TYPE",
    SUBTYPE_DROPDOWN: "Repository_Create_Contract/SUBTYPE_DROPDOWN",
    SUBTYPE_DROPDOWN_LIST: "Repository_Create_Contract/SUBTYPE_DROPDOWN_LIST",
    DYN_PARTICULAR_SUBTYPE: "Repository_Create_Contract/DYN_PARTICULAR_SUBTYPE",
    BU_LIST: "Repository_Create_Contract/BU_LIST",
    DYN_PARTICULAR_BU: "Repository_Create_Contract/DYN_PARTICULAR_BU",
    SELECT_FILE: "Repository_Create_Contract/SELECT_FILE",
    CONTINUE_BTTN: "Repository_Create_Contract/CONTINUE_BTTN",
    HEADER_LIST: "Repository_Contract_Details/HEADER_LIST",
    DYN_PARTICULAR_HEADER: "Repository_Contract_Details/DYN_PARTICULAR_HEADER",
    DYN_SUBHEADER_LIST: "Repository_Contract_Details/DYN_SUBHEADER_LIST",
    DYN_METADATA_INPUT: "Repository_Contract_Details/DYN_METADATA_INPUT",
    DNY_DROPDOWNFIELDLIST: "Repository_Contract_Details/DNY_DROPDOWNFIELDLIST",
    DYN_DROPDOWNFIELD: "Repository_Contract_Details/DYN_DROPDOWNFIELD",
    DYN_STRINGFIELD: "Repository_Contract_Details/DYN_STRINGFIELD",
    MONTH_DROPDOWN: "Repository_Contract_Details/MONTH_DROPDOWN",
    YEAR_DROPDOWN: "Repository_Contract_Details/YEAR_DROPDOWN",
    CURRENT_YEAR: "Repository_Contract_Details/CURRENT_YEAR",
    DNY_SELECT_DAY: "Repository_Contract_Details/DNY_SELECT_DAY",
    DNY_TEXTAREA: "Repository_Contract_Details/DNY_TEXTAREA",
    UPLOAD_DIGITAL_DOCUMENT: "Repository_Contract_Details/UPLOAD_DIGITAL_DOCUMENT",
    DNY_RADIO: "Repository_Contract_Details/DNY_RADIO",
    DNY_SUB_ENTITY_LIST: "Repository_Contract_Details/DNY_SUB_ENTITY_LIST",
    VIEW_ALL_BU: "Repository_Contract_Details/VIEW_ALL_BU",
    DELETE_BU: "Repository_Contract_Details/DELETE_BU",
    BUSINESS_UNIT_BTTN: "Repository_Contract_Details/BUSINESS_UNIT_BTTN",
    MANY_TO_MANY_POPUP_LIST: "Repository_Contract_Details/MANY_TO_MANY_POPUP_LIST",
    SELECT_ALL_BU: "Repository_Contract_Details/SELECT_ALL_BU",
    BU_DONE_BTTN: "Repository_Contract_Details/BU_DONE_BTTN",
    BU_CANCEL_BTTN: "Repository_Contract_Details/BU_CANCEL_BTTN",
    MANY_TO_MANY_DIV: "Repository_Contract_Details/MANY_TO_MANY_DIV",
    ALT_SUB_HEADER_LIST: "Repository_Contract_Details/ALT_SUB_HEADER_LIST",
    DNY_ATL_FIELD_LIST: "Repository_Contract_Details/DNY_ATL_FIELD_LIST",
    SAVE_ATL_BTTN: "Repository_Contract_Details/SAVE_ATL_BTTN",
    DYN_NEW_CONTRACT_NUMBER: "Repository_Contract_Details/DYN_NEW_CONTRACT_NUMBER",
    SAVE_CONTRACT_BTTN: "Repository_Contract_Details/SAVE_CONTRACT_BTTN",
    MANDATORY_ERROR_LABEL: "Repository_Contract_Details/MANDATORY_ERROR_LABEL",
    DYN_METADATA_LABELS: "Repository_Contract_Details/DYN_METADATA_LABELS",
    DYN_DROPDOWN_ELEMENTS: "Repository_Contract_Details/DYN_DROPDOWN_ELEMENTS",
    ALL_ROWS_BU_GRID: "Repository_Contract_Details/ALL_ROWS_BU_GRID",
    DYN_SUNENTITY_LIST_TO_SINGLE_ALTL: "Repository_Contract_Details/DYN_SUNENTITY_LIST_TO_SINGLE_ALTL",
    BU_GRID_HEADER: "Repository_Contract_Details/BU_GRID_HEADER",
    DNY_ALL_COLUMN_DATA_FROM_BUGRID: "Repository_Contract_Details/DNY_ALL_COLUMN_DATA_FROM_BUGRID",
    DNY_ALT_HEADER_DATA: "Repository_Contract_Details/ALT_HEADER_DATA",
    DYN_ATL_COLUMN_DATA: "Repository_Contract_Details/DYN_ATL_COLUMN_DATA",
    DYN_NORMAL_TEXTBOX_COMMON: "Auro_Repository_Contract_Details/DYN_NORMAL_TEXTBOX_COMMON",
    MULTI_DYN_DIGITAL_CONTRACT_METADATA: "Auro_Repository_Contract_Details/MULTI_DYN_DIGITAL_CONTRACT_METADATA",
    DYN_RADIO_BUTTON_COMMON: "Auro_Repository_Contract_Details/DYN_RADIO_BUTTON_COMMON",
    DNY_DROPDOWN_COMMON: "Auro_Repository_Contract_Details/DNY_DROPDOWN_COMMON",
    DYN_SUBHEADER_COMMON: "Auro_Repository_Contract_Details/DYN_SUBHEADER_COMMON",
    EXPAND_OR_COLLAPSE_ALL: "Auro_Repository_Contract_Details/EXPAND_OR_COLLAPSE_ALL",
    DYN_METADATA_NAME_COMMON: "Auro_Repository_Contract_Details/DYN_METADATA_NAME_COMMON",
    DNY_ALL_SUBHEADER_EXPAND_ICON: "Auro_Repository_Contract_Details/DNY_ALL_SUBHEADER_EXPAND_ICON",
    DNY_HEADER_LABEL_COUNT: "Auro_Repository_Contract_Details/DNY_HEADER_LABEL_COUNT",
    DNY_ALL_SUBHEADER_COLLAPSE_ICON: "Auro_Repository_Contract_Details/DNY_ALL_SUBHEADER_COLLAPSE_ICON",
    CONTRACT_NAME_METADATA: "Auro_Repository_Contract_Details/CONTRACT_NAME_METADATA",
    EXPAND_OR_COLLAPSE_DOCUMENT_PANEL: "Auro_Repository_Contract_Details/EXPAND_OR_COLLAPSE_DOCUMENT_PANEL",
    DOCUMENT_PANEL: "Auro_Repository_Contract_Details/DOCUMENT_PANEL",
    NO_DATA_TO_PREVIEW: "Auro_Repository_Contract_Details/NO_DATA_TO_PREVIEW",
    DOCUMENT_PANEL_DROPDOWN: "Auro_Repository_Contract_Details/DOCUMENT_PANEL_DROPDOWN",
    DOCUMENT_PANEL_VERSION_DROPDOWN: "Auro_Repository_Contract_Details/DOCUMENT_PANEL_VERSION_DROPDOWN",
    DOCUMENT_PANEL_VERSION_DROPDOWN_LIST: "Auro_Repository_Contract_Details/DOCUMENT_PANEL_VERSION_DROPDOWN_LIST",
    DOCUMENT_MENU: "Auro_Repository_Contract_Details/DOCUMENT_MENU",
    CONTRACT_DETAILS_TAB: "Repository_Contract_Details/CONTRACT_DETAILS_TAB",
    REPLACE_DOCUMENT: "Repository_Contract_Details/REPLACE_DOCUMENT",
    CLM_Visible_Element: "Repository_Contract_Details/CLM_Visible_Element",
    DYN_PARTICULAR_HEADER_COUNT: "Repository_Contract_Details/DYN_PARTICULAR_HEADER_COUNT",
    DROPDOWN_FIELD_SEARCH_BOX: "Repository_Contract_Details/DROPDOWN_FIELD_SEARCH_BOX",
    DNY_DROPDOWN_SEARCHED_VALUE: "Repository_Contract_Details/DNY_DROPDOWN_SEARCHED_VALUE",
    PROCESSING_REQUEST_LOADER: "Repository_Contract_Details/PROCESSING_REQUEST_LOADER",
    CONTRACT_STATUS_OPTION_LIST: "Repository/CONTRACT_STATUS_OPTION_LIST",
    FIRST_DASHBOARD_WIDGET: "Repository/FIRST_DASHBOARD_WIDGET",
    MANAGE_CONTRACT_TAB: "Repository/MANAGE_CONTRACT_TAB",
    CONTRACT_DETAILS_MENU: "Repository_Contract_Details/CONTRACT_DETAILS_MENU",
    WATCHLIST_ICON: "Repository_Contract_Details/WATCHLIST_ICON",
    MONTH_OPTION_LIST: "Repository_Contract_Details/MONTH_OPTION_LIST",
    YEAR_OPTION_LIST: "Repository_Contract_Details/YEAR_OPTION_LIST",
    DAY_OPTION_LIST: "Repository_Contract_Details/DAY_OPTION_LIST",
    CURRENT_DAY_OPTION: "Repository_Contract_Details/CURRENT_DAY_OPTION",
    ALREADY_SELECTED_DAY: "Repository_Contract_Details/ALREADY_SELECTED_DAY",
    DOCUMENT_DROPDOWN_FIRST_OPTION: "Auro_Repository_Contract_Details/DOCUMENT_DROPDOWN_FIRST_OPTION",
    VERSION_DROPDOWN_FIRST_OPTION: "Auro_Repository_Contract_Details/VERSION_DROPDOWN_FIRST_OPTION",
    COLLAPSE_BASIC_DETAILS_SUBHEADER: "Auro_Repository_Contract_Details/COLLAPSE_BASIC_DETAILS_SUBHEADER",
    // ################################ AURORA-554 ###############################################
    SETUP_TAB: "CLM_Home/SETUP_TAB",
    SETUP_PRODUCT_CONFIG_TAB: "CLM_Home/SETUP_PRODUCT_CONFIG_TAB",
    APPLICATION_SETTINGS: "Product_configuration/APPLICATION_SETTINGS",
    IS_CP_MANDTRY_CHECK_BOX: "Product_configuration/IS_CP_MANDTRY_CHECK_BOX",
    // ################################ AURORA-554 ###############################################
    //################################# AURORA-927 ##############################################
    LINKED_CONTRACT_MENU: "Repository/LINKED_CONTRACT_MENU",
    DYN_CONTRACT_HIERACHY_OPTION: "Repository/DYN_CONTRACT_HIERACHY_OPTION",
    HIERARCHY_STATUS_DROPDOWN: "Repository/HIERARCHY_STATUS_DROPDOWN",
    DYN_HIERARCHY_STATUS_VALUE: "Repository/DYN_HIERARCHY_STATUS_VALUE",
    DYN_CONTACT_HEADER_LABEL: "Repository/DYN_CONTACT_HEADER_LABEL",
    CONTRACT_LINK_HAVING_AMENDMENT: "Repository/CONTRACT_LINK_HAVING_AMENDMENT",
    //################################# AURORA-66 ##############################################
    DYN_SIDE_NAVIGATION_BAR_LINK: "Repository/DYN_SIDE_NAVIGATION_BAR_LINK",
};
