export let CommonComponentObject = {
    SearchAndSelectDropdown_Option : "CommonKeyword/DROP_DOWN_OPTION",
    LOADING_SPINNER: "CommonKeyword/LOADING_SPINNER",
    ALL_COLUMN_HEADER_TEXT: "CommonKeyword/ALL_COLUMN_HEADER_TEXT",
    HAMBURGER_MENU: "CommonKeyword/HAMBURGER_MENU",
    MENU_PANEL: "CommonKeyword/MENU_PANEL",
    SEARCH_TEXTBOX_CROSS_ICON: "CommonKeyword/SEARCH_TEXTBOX_CROSS_ICON",
    LEFT_ARROW_BUTTON: "ViewPage/LEFT_ARROW_BUTTON",
    USER_PROFILE_MENU: "CommonKeyword/USER_PROFILE_MENU",
    MANAGE_PROFILE_OPTION: "Home/UserProfileMenu/MANAGE_PROFILE_OPTION",
    USER_PREFERENCES_TAB: "Home/ManageProfile/USER_PREFERENCES_TAB",
    CURRENCY_DROPDOWN: "Home/UserPreferences/CURRENCY_DROPDOWN",
    DISPLAY_NAME: "ManageProfile/DISPLAY_NAME",
};
