"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.prop = void 0;
exports.prop = {
    "url": "https://ftssoha.ultria.com/sso/login",
    "browser": "chrome",
    //"browser": "firefox",
    "host": "127.0.0.1",
    "restart": true,
    "port": 4444,
    "windowSize": "maximize",
    "stepFilePath": "./steps_file",
    "projectName": "aurora_new-1",
    "UserTable": "aurora_credentials",
    "testdataTable": "aurora_testdata",
    "DBhost": "10.10.1.21",
    "DBdatabase": "aurora_automation",
    "DBuser": "aurora_automation",
    "DBpassword": "aurora_automation",
    "SETUP": "AURORAFTSETUP",
    "TENANT": "LM",
    "LOGIN_WITH_PASSWORD_MANAGER": false,
    "isCoa": false,
    "runOnGrid": false,
    "USERNAME": "admin.lm@ultria.com",
    "PASSWORD": "Asdf@123",
    "DEFAULT_WAIT": 2,
    "DEFAULT_LOW_WAIT": 15,
    "DEFAULT_MEDIUM_WAIT": 20,
    "DEFAULT_HIGH_WAIT": 30,
    "CONDITIONAL_WAIT": 50,
    "uiElementTable": "aurora_ui_elements",
    "AURORAFTSETUP_uiElementTable": "auroraftsetup_lm_ui_elements",
    "JiraloggingFlag": "false",
};
