"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.basicInformarationElements = void 0;
/**
 * Used to create an element object of basic information and contract details page
 *
 * @author somnath.k
 *
 *
 */
exports.basicInformarationElements = {
    UPLOAD_CONTRACT_IN_AURORA_BTTN: "Repository/UPLOAD_CONTRACT_IN_AURORA_BTTN",
    PAGE_LOAD_ELEMENT: "Basic_Information/PAGE_LOAD_ELEMENT",
    BROWSER_FILE: "Basic_Information/BROWSER_FILE",
    CONTINUE_BTTN: "Basic_Information/CONTINUE_BTTN",
    ALL_FIELDS_DATA: "Basic_Information/ALL_FIELDS_DATA",
    ALL_FIELDS_MANDATORY_SYMBOL: "Basic_Information/ALL_FIELDS_MANDATORY_SYMBOL",
    ALL_FIELDS_MANDATORY_MSG: "Basic_Information/ALL_FIELDS_MANDATORY_MSG",
    DYNAMIC_DROPDOWN_OPTION_LIST: "Basic_Information/DYNAMIC_DROPDOWN_OPTION_LIST",
    DYNAMIC_DROPDOWNS: "Basic_Information/DYNAMIC_DROPDOWNS",
    NO_ITEMS_FOUND_MSG: "Basic_Information/NO_ITEMS_FOUND_MSG",
    BU_FIELD_OPTION_LIST: "Basic_Information/BU_FIELD_OPTION_LIST",
    DNY_BU_VALUE_IN_BOX: "Basic_Information/DNY_BU_VALUE_IN_BOX",
    DNY_DELETE_INDIVIDUAL_BU_IN_BOX: "Basic_Information/DNY_DELETE_INDIVIDUAL_BU_IN_BOX",
    CLEAR_ALL_BU_ICON: "Basic_Information/CLEAR_ALL_BU_ICON",
    SEARCH_BOX_INSIDE_DROPDOWN: "Basic_Information/SEARCH_BOX_INSIDE_DROPDOWN",
    INVALID_FORMAT_ERROR_POPUP: "Basic_Information/INVALID_FORMAT_ERROR_POPUP",
    ERROR_POPUP_OK_BUTTON: "Basic_Information/ERROR_POPUP_OK_BUTTON",
    BLANK_DOCUMENT_ERROR_POPUP: "Basic_Information/BLANK_DOCUMENT_ERROR_POPUP",
    ZERO_KB_DOCUMENT_ERROR_POPUP: "Basic_Information/ZERO_KB_DOCUMENT_ERROR_POPUP",
    GREATER_SIZE_ERROR_POPUP: "Basic_Information/GREATER_SIZE_ERROR_POPUP",
    FILE_UPLOAD_PROGRESS_BAR: "Basic_Information/FILE_UPLOAD_PROGRESS_BAR",
    REPLACE_DOCUMENT_POPUP: "Basic_Information/REPLACE_DOCUMENT_POPUP",
    CANCEL_BUTTON_IN_REPLACE_POPUP: "Basic_Information/CANCEL_BUTTON_IN_REPLACE_POPUP",
    REPLACE_BUTTON_IN_POPUP: "Basic_Information/REPLACE_BUTTON_IN_POPUP",
    CANCEL_BTTN_IN_DRAG_AND_DROP_BOX: "Basic_Information/CANCEL_BTTN_IN_DRAG_AND_DROP_BOX",
    DRAG_AND_DROP_BOX_DETAILS: "Basic_Information/DRAG_AND_DROP_BOX_DETAILS",
    DNY_PARTICULAR_DRAG_AND_DROP_DETAIL: "Basic_Information/DNY_PARTICULAR_DRAG_AND_DROP_DETAIL",
    DNY_UPLOADED_FILE_NAME_IN_DRAG_AND_DROP_BOX: "Basic_Information/DNY_UPLOADED_FILE_NAME_IN_DRAG_AND_DROP_BOX",
    FILE_LOADER_IMAGE: "Basic_Information/FILE_LOADER_IMAGE",
    TICK_ICON_IN_DRAG_AND_DROP_BOX: "Basic_Information/TICK_ICON_IN_DRAG_AND_DROP_BOX",
    REPLACE_BTTN_IN_DRAG_AND_DROP_BOX: "Basic_Information/REPLACE_BTTN_IN_DRAG_AND_DROP_BOX",
    CANCEL_BTTN_IN_NEW_CONTRACT: "Basic_Information/CANCEL_BTTN_IN_NEW_CONTRACT",
    DISCARD_CONTRACT_POPUP: "Basic_Information/DISCARD_CONTRACT_POPUP",
    ALL_FIELDS_METADATA_LABEL: "Basic_Information/ALL_FIELDS_METADATA_LABEL",
    DISCARD_BUTTON_IN_DISCARD_POPUP: "Basic_Information/DISCARD_BUTTON_IN_DISCARD_POPUP",
    CANCEL_BTTN_IN_DISCARD_POPUP: "Basic_Information/CANCEL_BTTN_IN_DISCARD_POPUP",
    PLEASE_WAIT_POPUP: "Basic_Information/PLEASE_WAIT_POPUP",
    DNY_TYPE_SUBTYPE_IN_HEADER: "Auro_Repository_Contract_Details/DNY_TYPE_SUBTYPE_IN_HEADER",
    LOGOUT_BTTN: "Repository/LOGOUT_BTTN",
    OVERVIEW_HEADER: "Basic_Information/OVERVIEW_HEADER",
    YES_BTTN_IN_POPUP: "Basic_Information/YES_BTTN_IN_POPUP"
};
